version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secure_pass
      - MONGO_INITDB_DATABASE=test
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6:
